name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Backend setup and tests
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black isort mypy
    
    - name: Install pre-commit hooks
      run: |
        pre-commit install
    
    - name: Run Flake8
      run: |
        flake8 .
    
    - name: Run Black check
      run: |
        black --check .
    
    - name: Run Isort check
      run: |
        isort --check-only .
    
    - name: Run Mypy
      run: |
        mypy .
    
    - name: Run backend tests
      run: |
        python -m pytest tests/ -v
    
    # Frontend setup and build
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build